name: Build & Push Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # needed for GHCR
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 1) Build & push WordPress image
      - name: Build & push WordPress image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Example tag for WP
          tags: ghcr.io/samubhutan/govtech_czc_wordpress:latest

      # 2) Build & push MariaDB image
      - name: Build & push DB image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.db
          push: true
          # Example tag for DB
          tags: ghcr.io/samubhutan/govtech_czc_mariadb:latest
