name: Build & Push Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # needed for GHCR

    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 1) Build & push bilingual WordPress image
      - name: Build & push WordPress image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/samubhutan/govtech_czc_wordpress:latest
            ghcr.io/samubhutan/govtech_czc_wordpress:${{ github.run_number }}

      # 2) Build & push MariaDB image (shared by both WP sites)
      - name: Build & push DB image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.db
          push: true
          tags: |
            ghcr.io/samubhutan/govtech_czc_mariadb:latest
            ghcr.io/samubhutan/govtech_czc_mariadb:${{ github.run_number }}
